# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Chenyang Gao (郜晨阳)
title: Researcher
website: https://wettera.github.io/CV_Chinese.pdf
website_title: 中文简历
email: 11710904@mail.sustech.edu.cn
# email_title: Email (Email title override)
phone: (+86)18337461359
# phone_title: Phone (Phone title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: wettera
linkedin_username: 晨阳-郜


#Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
gtm: "GTM-0000000"
gtag: "UA-00000000-0"
google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a fourth-year undergraduate at [Department of Computer Science and Engineering](http://cse.sustech.edu.cn/en/), [Southern University of Science and Technology](https://www.sustech.edu.cn/en/) under the supervision of [Prof. Feng Zheng](https://faculty.sustech.edu.cn/fengzheng/en/).
  In October 2020, I was admitted to pursue a Master degree in [Huazhong University of Science and Techology](http://english.hust.edu.cn/), under the supervision of [Prof. Xiang Bai](http://122.205.5.5:8071/~xbai/) without entrance examination. 
  My research interests include **Computer Vision** and **Deep Learning**.


content:

  - title: Education
    layout: list
    content:
      - layout: top
        title: Southern University of Science and Technology
        sub_title: Computer Science
        caption: 2017.9 — 2021.6
        #quote: >
        # Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
         - GPA: 3.57/4.0
         - Select Honors: National Inspirational Scholarship(2018) <br>
           [Tencent Rhino-Bird Elite Training Program](https://join.qq.com/news_detail.html?id=232)(2020) 
          

  - title: Research Experience
    layout: list
    content:
      #- layout: right
      #  title: National University of Singapore
      #  sub_title: School of Computing
      #  caption: 2019.6 — 2019.7
      # quote: >
      # Short description of the company (optional)
      # description: | # this will include new lines to allow paragraphs
      #  - Summer Workshop related to artificial intelligence and security
      #  - Grade: A

      - layout: top
        title: Tencent YouTu Lab
        sub_title: Research intern
        caption: 2020.6 — 2020.9
      # quote: >
      # Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
         - Research on **text based person search** task
         - Wrote one paper and two invention patents

  - title: Publications
    layout: list
    content:
      - layout: right
        description: | # this will include new lines to allow paragraphs
          ## Papers:
          - Contextual Non-Local Alignment over Full-Scale Representation for Text-Based Person Search <br>
          **Chenyang Gao**, Guanyu Cai, Xinyang Jiang, Feng Zheng, Jun Zhang, Yifei Gong, Pai Peng, Xiaowei Guo and Xing Sun <br>
          Arxiv: 2101.03036, 2021.[[PDF](https://arxiv.org/pdf/2101.03036.pdf)] [[Code](https://github.com/TencentYoutuResearch/PersonReID-NAFS)]

          ## Invention Patents:
          - **郜晨阳**，蔡冠羽，蒋忻洋，张均，宫毅非，孙星，郭晓威 一种基于多尺度文本搜人方法 (已提交至腾讯优图实验室相关负责人)
          - **郜晨阳**，蔡冠羽，蒋忻洋，张均，宫毅非，孙星，郭晓威 一种基于跨尺度注意力机制的文本搜人方法 (已提交至腾讯优图实验室相关负责人)




 


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
